import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { WEBHOOK_PATHS } from '../src/lib/n8nWebhookPaths.js'
import { loadCodeNode, runCodeNode } from './workflowHarness.js'

// ─── "Agent — weekly email drafts" ─────────────────────────────────────────
// A hand-written workflow (not generated by gen_workflows.py), so nothing but
// this file checks it before it reaches the box.

const here = path.dirname(fileURLToPath(import.meta.url))
const NAME = 'Agent — weekly email drafts'
const workflow = JSON.parse(fs.readFileSync(path.join(here, 'workflows', `${NAME}.json`), 'utf8'))
const nodes = workflow.nodes
const names = new Set(nodes.map(n => n.name))
const byName = n => nodes.find(x => x.name === n)

describe('wiring', () => {
  it('every connection points at a real node', () => {
    const dangling = []
    for (const [src, outs] of Object.entries(workflow.connections)) {
      if (!names.has(src)) dangling.push(src)
      for (const group of outs.main || []) for (const c of group || []) if (!names.has(c.node)) dangling.push(`${src} -> ${c.node}`)
    }
    expect(dangling).toEqual([])
  })

  it('runs Monday after the research run, which starts at 06:00 UTC', () => {
    const cron = byName('Monday 07:30 UTC').parameters.rule.interval[0].expression
    expect(cron).toBe('30 7 * * 1')
    const research = JSON.parse(fs.readFileSync(path.join(here, 'workflows', 'Agent — weekly research run.json'), 'utf8'))
    const researchCron = research.nodes.find(n => n.type === 'n8n-nodes-base.scheduleTrigger').parameters.rule.interval[0].expression
    expect(researchCron).toBe('0 6 * * 1')
  })

  it('never retries the paid call, and does not stop on its error', () => {
    // n8n's retry re-sends the whole node: that is how one research run was
    // billed twice. A second call this week is refused for free anyway.
    const http = nodes.filter(n => n.type === 'n8n-nodes-base.httpRequest')
    expect(http).toHaveLength(1)
    expect(http[0].retryOnFail).not.toBe(true)
    expect(http[0].onError).toBe('continueRegularOutput')
    expect(http[0].parameters.url).toContain('/api/agent/emailWeekly')
    expect(JSON.stringify(http[0].parameters.headerParameters)).toContain('$env.AGENT_RUN_SECRET')
  })

  it('answers the app on the path the Vercel proxy forwards to', () => {
    expect(byName('Button (app)').parameters.path).toBe(WEBHOOK_PATHS.emailWeekly)
    expect(WEBHOOK_PATHS.emailWeekly).toBe('arak-email-weekly')
  })
})

describe('the app button', () => {
  it('forwards the caller\'s token to exactly one agent route', async () => {
    const { out, calls } = await runCodeNode(loadCodeNode(NAME, 'Forward to the agent'), {
      env: { AGENT_BASE_URL: 'http://agent:3000' },
      input: { body: { access_token: 'user-jwt', workspace_id: 'ws-1', action: 'run', url: 'http://elsewhere' } },
      routes: [['http://agent:3000/api/agent/emailWeekly', () => ({ statusCode: 200, body: { ok: true, options: 3 } })]],
    })
    expect(out).toEqual({ ok: true, options: 3 })
    expect(calls).toHaveLength(1)
    expect(calls[0].url).toBe('http://agent:3000/api/agent/emailWeekly')
    expect(calls[0].body).toEqual({ workspace_id: 'ws-1', trigger: 'manual' })
  })

  it('refuses without a token and calls nothing', async () => {
    const { out, calls } = await runCodeNode(loadCodeNode(NAME, 'Forward to the agent'), {
      env: { AGENT_BASE_URL: 'http://agent:3000' }, input: { body: { workspace_id: 'ws-1' } },
    })
    expect(out.ok).toBe(false)
    expect(calls).toHaveLength(0)
  })

  it('reports a skipped week and a failure in words', async () => {
    const skip = await runCodeNode(loadCodeNode(NAME, 'What happened'), { env: {}, input: { ok: true, skipped: 'No marketing contacts yet' } })
    expect(skip.out.summary).toContain('Skipped')
    const fail = await runCodeNode(loadCodeNode(NAME, 'What happened'), { env: {}, input: { ok: false, error: 'cap', capped: true } })
    expect(fail.out.summary).toContain('monthly AI budget')
  })
})
