import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadCodeNode, runCodeNode } from './workflowHarness.js'

// ─── "Email — cold sender" ─────────────────────────────────────────────────
// Hand-written (not generated by gen_workflows.py), so this file is the only
// check it gets before it reaches the box.

const here = path.dirname(fileURLToPath(import.meta.url))
const NAME = 'Email — cold sender'
const workflow = JSON.parse(fs.readFileSync(path.join(here, 'workflows', `${NAME}.json`), 'utf8'))
const nodes = workflow.nodes
const names = new Set(nodes.map(n => n.name))
const byName = n => nodes.find(x => x.name === n)

describe('wiring', () => {
  it('every connection points at a real node', () => {
    const dangling = []
    for (const [src, outs] of Object.entries(workflow.connections)) {
      if (!names.has(src)) dangling.push(src)
      for (const group of outs.main || []) for (const c of group || []) if (!names.has(c.node)) dangling.push(`${src} -> ${c.node}`)
    }
    expect(dangling).toEqual([])
  })

  it('runs every 10 minutes; the app, not the schedule, knows the sending hours', () => {
    expect(byName('Every 10 minutes').parameters.rule.interval[0].expression).toBe('*/10 * * * *')
  })

  it('calls the cold run on the app with the cron secret, once, never retried', () => {
    const http = nodes.filter(n => n.type === 'n8n-nodes-base.httpRequest')
    expect(http).toHaveLength(1)
    expect(http[0].retryOnFail).not.toBe(true)
    expect(http[0].onError).toBe('continueRegularOutput')
    expect(http[0].parameters.method).toBe('GET')
    expect(http[0].parameters.url).toContain('/api/email/cold-tick')
    expect(http[0].parameters.url).toContain('$env.APP_BASE_URL')
    expect(JSON.stringify(http[0].parameters.headerParameters)).toContain('$env.CRON_SECRET')
    // Under Vercel's 300s ceiling, so n8n never gives up on a run still sending.
    expect(http[0].parameters.options.timeout).toBeLessThan(300_000)
  })

  it('the box passes the app address to n8n', () => {
    const compose = fs.readFileSync(path.join(here, 'docker', 'docker-compose.yml'), 'utf8')
    expect(compose).toMatch(/- APP_BASE_URL=https:\/\//)
  })
})

describe('what a person reads', () => {
  const node = loadCodeNode(NAME, 'What happened')

  it('says plainly when the secret is missing on the box', async () => {
    const { out } = await runCodeNode(node, { env: {}, input: { ok: false } })
    expect(out.summary).toMatch(/CRON_SECRET is not set on the box/)
  })

  it('reports outside hours without noise', async () => {
    const { out } = await runCodeNode(node, { env: { CRON_SECRET: 'x' }, input: { ok: true, window: false, nextWindow: '2026-10-04T06:00:00.000Z' } })
    expect(out.summary).toBe('Outside sending hours. Next window: 2026-10-04T06:00:00.000Z.')
  })

  it('lists each mailbox and what it did', async () => {
    const { out } = await runCodeNode(node, {
      env: { CRON_SECRET: 'x' },
      input: { ok: true, window: true, sent: 1, skipped: 0, failed: 0, workspaces: [{ mailboxes: [{ mailbox: 'a@x.com', reason: 'Sent first email to p@q.com.' }] }] },
    })
    expect(out.summary).toBe('Sent 1, skipped 0, failed 0.')
    expect(out.mailboxes).toEqual(['a@x.com: Sent first email to p@q.com.'])
  })
})
